import type { ChallengeConfig } from '@/data/types'
import codeLifeExercises from './codelife-exercises.json'

// Local exercises (0_0_X) loaded at build time
const modules = import.meta.glob('./clExercises/*.json', { eager: true }) as Record<
  string,
  { default: ChallengeConfig }
>

const allChallenges = new Map<string, ChallengeConfig>()
const exercises: ChallengeConfig[] = []

// Local exercises first (take precedence)
for (const mod of Object.values(modules)) {
  const config = mod.default
  allChallenges.set(config.id, config)
  exercises.push(config)
}

// CodeLife exercises (generated by scripts/sync-codelife.mjs)
for (const ex of codeLifeExercises as ChallengeConfig[]) {
  if (!allChallenges.has(ex.id)) {
    allChallenges.set(ex.id, ex)
    exercises.push(ex)
  }
}

export function getChallenge(id: string): ChallengeConfig | undefined {
  return allChallenges.get(id)
}

export function getAllChallenges(): ChallengeConfig[] {
  return exercises
}

export function getAllChallengeIds(): string[] {
  return exercises.map(c => c.id)
}
